application: lolay-citygrid-monitor
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: html

- url: /(.*\.(html|gif|png|jpg))
  static_files: \1
  upload: (.*\.(html|gif|png|jpg))

- url: .*
  script: main.app
